# Generated by Django 5.0.1 on 2024-01-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.EmailField(max_length=254, verbose_name='')),
                ('To', models.CharField(default='', max_length=50)),
                ('Transaction_id', models.CharField(default='', max_length=10000)),
                ('Transaction_date', models.DateTimeField(auto_now=True)),
                ('Transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Transaction_status', models.CharField(blank=True, choices=[('Success', 'Success'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('Aborted', 'Aborted'), ('Unconfirmed', 'Unconfirmed'), ('Cancelled', 'Cancelled')], max_length=255, null=True)),
                ('Transaction_remark', models.CharField(default='', max_length=200)),
                ('Transaction_type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address main')),
                ('first_name', models.CharField(blank=True, max_length=130, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('contact_no', models.BigIntegerField(blank=True, null=True, verbose_name='contact no')),
                ('date_joined', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
