# Generated by Django 5.0.1 on 2024-01-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='first name'),
        ),
    ]
