# Generated by Django 5.0.1 on 2024-01-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_journal_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Teacher',
            field=models.BooleanField(default=False),
        ),
    ]
