# Generated by Django 5.0 on 2024-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsession',
            old_name='custom_field',
            new_name='IP',
        ),
        migrations.AddField(
            model_name='customsession',
            name='access_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsession',
            name='refresh_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
