# Generated by Django 5.0 on 2024-02-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_custom_field_customsession_ip_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsession',
            old_name='access_token',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='customsession',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super_Admin', 'Super Admin'), ('Merchant', 'Merchant')], default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session'),
        ),
    ]
