# Generated by Django 5.0 on 2024-02-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customsession_id_alter_customsession_session'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session', unique=True),
        ),
    ]
